import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CustomProvider } from "@/utils/CustomProvider";
import { cookies } from "next/headers";
import { getTokens } from "next-firebase-auth-edge";
import { clientConfig, serverConfig } from "@/config";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Navbar";

// import { useRouter } from "next/router";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const router = useRouter();
  const tokens = await getTokens(cookies(), {
    apiKey: clientConfig.apiKey,
    cookieName: serverConfig.cookieName,
    cookieSignatureKeys: serverConfig.cookieSignatureKeys,
    serviceAccount: serverConfig.serviceAccount,
  });

  return (
    <html lang="en">
      {/* <Suspense> */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CustomProvider tokens={tokens}>
          <ToastContainer />
          {tokens && <Navbar tokens={tokens} />}
          {children}
        </CustomProvider>
      </body>
      {/* </Suspense> */}
    </html>
  );
}
